openapi: 3.0.3
info:
  title: Swagger Library
  description: Simple swagger of books-library service
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              required:
                - login
                - password
                - first_name
                - last_name
                - birth_date
              type: object
              properties:
                login:
                  type: string
                  default: "admin"
                  description: "user login"
                password:
                  type: string
                  default: "admin"
                  description: "user password"
                first_name:
                  type: string
                  default: "admin"
                  description: "user name"
                last_name:
                  type: string
                  default: "admin"
                  description: "user surname"
                patronymic:
                  type: string
                  description: "user patronymic"
                  default: "admin"
                birth_date:
                  type: string
                  description: "user birth date"
                  default: "2000-12-01"

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "ok"
        400:
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "invalid request"
        422:
          description: login already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "login already exists"

  /auth/login:
    post:
      tags:
        - Auth
      summary: User authentication
      requestBody:
        content:
          application/json:
            schema:
              required:
                - login
                - password
              type: object
              properties:
                login:
                  type: string
                  default: "admin"
                  description: "user login"
                password:
                  type: string
                  default: "admin"
                  description: "user password"
      responses:
        400:
          description: wrong credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "invalid credentials"

        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "auth token"


  /book:
    post:
      tags:
        - Book
      summary: Create new book
      requestBody:
        content:
          application/json:
            schema:
              required:
                - title
                - description
                - age_group
                - publishing_date
              type: object
              properties:
                title:
                  type: string
                  description: "book title"
                  default: "Граф Монте-Кристо"
                description:
                  type: string
                  description: "book description"
                  default: "Приключенческий роман Александра Дюма"
                age_group:
                  type: integer
                  description: "book minimum age"
                  default: 18
                publishing_date:
                  type: string
                  description: "book publishing date"
                  default: "2000-12-01"
      responses:
        401:
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "unauthorized"
        400:
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "invalid request"
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "book id"
                    default: 1
                  title:
                    type: string
                    description: "book title"
                    default: "Граф Монте-Кристо"
                  description:
                    type: string
                    description: "book description"
                    default: "Приключенческий роман Александра Дюма"
                  age_group:
                    type: integer
                    description: "book minimum age"
                    default: 18
                  publishing_date:
                    type: string
                    description: "book publishing date"
                    default: "2000-12-01"
  /book/{id}:
    put:
      tags:
        - Book
      summary: Update existing book
      parameters:
        - in: path
          name: id
          description: book id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              required:
                - title
                - description
                - age_group
                - publishing_date
              type: object
              properties:
                title:
                  type: string
                  description: "book title"
                  default: "Граф Монте-Кристо"
                description:
                  type: string
                  description: "book description"
                  default: "Приключенческий роман Александра Дюма"
                age_group:
                  type: integer
                  description: "book minimum age"
                  default: 18
                publishing_date:
                  type: string
                  description: "book publishing date"
                  default: "2000-12-01"
      responses:
        200:
          description: OK
        400:
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "invalid request"
        401:
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "unauthorized"
        404:
          description: book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "book not found"
    get:
      tags:
        - Book
      summary: Get book by id
      parameters:
        - in: path
          name: id
          description: book id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: "book title"
                    default: "Граф Монте-Кристо"
                  description:
                    type: string
                    description: "book description"
                    default: "Приключенческий роман Александра Дюма"
                  age_group:
                    type: integer
                    description: "book minimum age"
                    default: 18
                  publishing_date:
                    type: string
                    description: "book publishing date"
                    default: "2000-12-01"
        400:
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "invalid request"
        401:
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "unauthorized"
        404:
          description: book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "book not found"
    delete:
      tags:
        - Book
      summary: Delete book by id
      parameters:
        - in: path
          name: id
          description: book id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: OK
        400:
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "invalid request"
        401:
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "unauthorized"
        404:
          description: book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "error"
                  error:
                    type: string
                    default: "book not found"

