// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	model "simple-golang-api/internal/repository/books/model"

	mock "github.com/stretchr/testify/mock"
)

// BooksRepo is an autogenerated mock type for the BooksRepo type
type BooksRepo struct {
	mock.Mock
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *BooksRepo) DeleteBook(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBook provides a mock function with given fields: ctx, id
func (_m *BooksRepo) GetBook(ctx context.Context, id int64) (*model.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 *model.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Book); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertBook provides a mock function with given fields: ctx, book
func (_m *BooksRepo) InsertBook(ctx context.Context, book *model.Book) error {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for InsertBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Book) error); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBook provides a mock function with given fields: ctx, id, book
func (_m *BooksRepo) UpdateBook(ctx context.Context, id int64, book *model.Book) error {
	ret := _m.Called(ctx, id, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *model.Book) error); ok {
		r0 = rf(ctx, id, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBooksRepo creates a new instance of BooksRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBooksRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BooksRepo {
	mock := &BooksRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
